import * as THREE from './vendor/three.module.js';
const KEY='ai-life-alpha-beta-v1';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x78a9b5);scene.fog=new THREE.Fog(0x78a9b5,48,125);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,220);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.querySelector('#game').append(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xc9ecff,0x29452f,1.45);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff1d0,2.4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.position.set(25,50,20);scene.add(sun);
const world=new THREE.Group();scene.add(world);const rnd=(a,b)=>a+Math.random()*(b-a);const dist=(a,b)=>a.q.position.distanceTo(b.q.position);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(130,130,20,20),new THREE.MeshStandardMaterial({color:0x355f3a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
const river=new THREE.Mesh(new THREE.PlaneGeometry(22,130),new THREE.MeshStandardMaterial({color:0x2b7890,transparent:true,opacity:.78,roughness:.25}));river.rotation.x=-Math.PI/2;river.position.set(-23,.035,0);world.add(river);
function tree(x,z,s=1){const q=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22*s,.34*s,2.4*s,8),new THREE.MeshStandardMaterial({color:0x5b3922}));trunk.position.y=1.2*s;trunk.castShadow=true;const crown=new THREE.Mesh(new THREE.ConeGeometry(1.25*s,2.8*s,9),new THREE.MeshStandardMaterial({color:0x28653a}));crown.position.y=3*s;crown.castShadow=true;q.add(trunk,crown);q.position.set(x,0,z);world.add(q);return q}
function rock(x,z,s=1){const m=new THREE.Mesh(new THREE.DodecahedronGeometry(.6*s),new THREE.MeshStandardMaterial({color:0x77776f,roughness:1}));m.position.set(x,.45*s,z);m.scale.y=.7;m.castShadow=true;m.receiveShadow=true;world.add(m);return m}
for(let i=0;i<75;i++){let x=rnd(-54,50),z=rnd(-54,54);if(Math.abs(x+23)<13)continue;tree(x,z,rnd(.7,1.25))}for(let i=0;i<48;i++){let x=rnd(-52,50),z=rnd(-52,52);if(Math.abs(x+23)<12)continue;rock(x,z,rnd(.55,1.2))}for(let i=0;i<150;i++){const g=new THREE.Mesh(new THREE.ConeGeometry(.08,.35,4),new THREE.MeshStandardMaterial({color:0x4c7b45}));g.position.set(rnd(-55,50),.17,rnd(-55,55));world.add(g)}
const fire=new THREE.Group();fire.position.set(2,0,7);world.add(fire);for(let i=0;i<5;i++){const log=new THREE.Mesh(new THREE.CylinderGeometry(.13,.16,1.1,7),new THREE.MeshStandardMaterial({color:0x633b21}));log.rotation.z=Math.PI/2;log.rotation.y=i*Math.PI/2;log.position.y=.25;log.castShadow=true;fire.add(log)}const flame=new THREE.Mesh(new THREE.ConeGeometry(.48,1.35,8),new THREE.MeshBasicMaterial({color:0xff9b35,transparent:true,opacity:.85}));flame.position.y=1;fire.add(flame);const glow=new THREE.PointLight(0xff9b35,3,12);glow.position.y=1;fire.add(glow);
const resourceNodes=[];for(let i=0;i<20;i++){const t=tree(rnd(-45,42),rnd(-48,48),.68);t.userData={type:'wood',amount:6};resourceNodes.push(t)}for(let i=0;i<20;i++){const r=rock(rnd(-45,42),rnd(-48,48),.8);r.userData={type:'stone',amount:5};resourceNodes.push(r)}
const agents=[];function makeAgent(name,model,col,x,z){const q=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0xc99572,roughness:.9});const cloth=new THREE.MeshStandardMaterial({color:col,roughness:.85});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.9,6,10),cloth);body.position.y=1.15;body.castShadow=true;const head=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),skin);head.position.y=2.05;head.castShadow=true;const armL=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.58,5,8),skin),armR=armL.clone(),legL=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.72,5,8),skin),legR=legL.clone();armL.position.set(-.48,1.2,0);armR.position.set(.48,1.2,0);legL.position.set(-.18,.55,0);legR.position.set(.18,.55,0);const ring=new THREE.Mesh(new THREE.RingGeometry(.62,.75,32),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:.8,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.03;ring.visible=false;q.add(body,head,armL,armR,legL,legR,ring);q.position.set(x,0,z);scene.add(q);const ne=document.createElement('div'),be=document.createElement('div'),th=document.createElement('div');ne.className='name';be.className='bubble';th.className='thinking';ne.textContent=name;document.body.append(ne,be,th);const e={id:name,name,model,col,q,armL,armR,legL,legR,ring,ne,be,th,energy:100,hunger:15,thirst:10,health:100,knowledge:0,wood:0,stone:0,food:0,state:'наблюдает',target:new THREE.Vector3(x+rnd(-15,15),0,z+rnd(-15,15)),memory:[],visited:new Set(),decisions:0,successful:0,failures:0,adaptations:0,interactions:0,cooperations:0,discoveries:0,critical:0,activePlan:null,decisionCooldown:0,thought:'Осматриваю мир.',trust:0,daysAlive:0};agents.push(e);return e}
const alpha=makeAgent('OpenAI','OpenAI',0x4db8e8,-7,0),beta=makeAgent('Cloude','Cloude',0xe48b55,7,0);
let started=localStorage.getItem(KEY+'-start')?Number(localStorage.getItem(KEY+'-start')):0;let paused=false,follow=null,auto=true,yaw=.7,pitch=.55,rad=30,last=performance.now(),events=[];const clockEl=document.querySelector('#clock');
function log(t){events.unshift(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})+' · '+t);events=events.slice(0,9);document.querySelector('#events').innerHTML=events.map(e=>`<div class="event">${e}</div>`).join('')}
function save(){if(!started)return;const data={started,agents:agents.map(a=>({energy:a.energy,hunger:a.hunger,thirst:a.thirst,health:a.health,knowledge:a.knowledge,wood:a.wood,stone:a.stone,food:a.food,memory:a.memory,decisions:a.decisions,successful:a.successful,failures:a.failures,adaptations:a.adaptations,interactions:a.interactions,cooperations:a.cooperations,discoveries:a.discoveries,trust:a.trust,daysAlive:a.daysAlive,x:a.q.position.x,z:a.q.position.z}))};localStorage.setItem(KEY,JSON.stringify(data))}
function load(){const raw=localStorage.getItem(KEY);if(!raw)return;try{const d=JSON.parse(raw);started=d.started;d.agents?.forEach((s,i)=>{const a=agents[i];Object.assign(a,s);a.q.position.set(s.x||a.q.position.x,0,s.z||a.q.position.z);a.memory=s.memory||[]})}catch(e){}}
function begin(){if(!started){started=Date.now();localStorage.setItem(KEY+'-start',String(started));localStorage.removeItem(KEY);log('🚀 Эксперимент начат. OpenAI и Cloude получили только мир и собственные базовые потребности.')}else log('↩️ Продолжаем ранее начатый эксперимент.');updateExperiment()}
const controlMenu=document.querySelector('#controlMenu');const controlOrb=document.querySelector('#controlOrb');const brainOrb=document.querySelector('#brainOrb');const rightPanel=document.querySelector('#rightPanel');controlOrb.onclick=()=>controlMenu.classList.toggle('open');brainOrb.onclick=()=>rightPanel.classList.toggle('open');document.querySelector('#closePanel').onclick=()=>rightPanel.classList.remove('open');
document.querySelector('#start').onclick=()=>{begin();controlMenu.classList.remove('open')};document.querySelector('#pause').onclick=()=>{paused=!paused;document.querySelector('#pause').textContent=paused?'▶️':'⏸';document.querySelector('#pause').title=paused?'Продолжить':'Пауза'};document.querySelector('#followA').onclick=()=>{follow=alpha;controlMenu.classList.remove('open')};document.querySelector('#followB').onclick=()=>{follow=beta;controlMenu.classList.remove('open')};document.querySelector('#free').onclick=()=>{follow=null;controlMenu.classList.remove('open')};document.querySelector('#auto').onclick=()=>{auto=!auto;document.querySelector('#auto').textContent=auto?'🎬':'⏺';controlMenu.classList.remove('open')};
function nearest(a,type){let best=null,bd=Infinity;for(const r of resourceNodes){if(!r.visible||r.userData.type!==type||r.userData.amount<=0)continue;const d=a.q.position.distanceTo(r.position);if(d<bd){bd=d;best=r}}return best}
function remember(a,text){a.memory.unshift({t:Date.now(),text});a.memory=a.memory.slice(0,20)}
function choose(a){a.decisions++;a.decisionCooldown=5+rnd(0,5);let reason='исследовать';let target=null;if(a.thirst>72){reason='искать воду';target=new THREE.Vector3(-23,0,a.q.position.z+rnd(-8,8))}else if(a.hunger>75){reason='искать еду';target=new THREE.Vector3(rnd(-15,40),0,rnd(-45,45))}else if(a.energy<25){reason='отдыхать';target=fire.position.clone()}else{const roll=Math.random();if(roll<.38){reason='исследовать';target=new THREE.Vector3(rnd(-48,45),0,rnd(-48,48))}else if(roll<.68){const r=nearest(a,'wood');if(r){reason='исследовать дерево';target=r.position.clone()}}else{const r=nearest(a,'stone');if(r){reason='исследовать камень';target=r.position.clone()}}}if(!target)target=new THREE.Vector3(rnd(-48,45),0,rnd(-48,48));a.target.copy(target);a.state=reason;a.thought='Решаю, что делать дальше.';a.th.style.display='block';a.th.textContent='💭 '+reason;remember(a,reason);return}
function act(a,dt){a.energy=Math.max(0,a.energy-dt*.035);a.hunger=Math.min(100,a.hunger+dt*.055);a.thirst=Math.min(100,a.thirst+dt*.075);if(a.energy<8||a.hunger>95||a.thirst>95)a.health=Math.max(0,a.health-dt*.08);else a.health=Math.min(100,a.health+dt*.015);if(a.health<20)a.critical+=dt;if(a.decisionCooldown<=0)choose(a);else a.decisionCooldown-=dt;const d=a.target.clone().sub(a.q.position);d.y=0;if(d.lengthSq()>.8){d.normalize();a.q.position.addScaledVector(d,dt*.72);a.q.lookAt(a.q.position.clone().add(d));const sw=Math.sin(performance.now()/130)*.5;a.armL.rotation.z=sw;a.armR.rotation.z=-sw;a.legL.rotation.x=-sw*.55;a.legR.rotation.x=sw*.55}else{a.armL.rotation.z=a.armR.rotation.z=a.legL.rotation.x=a.legR.rotation.x=0;a.energy=Math.min(100,a.energy+dt*.04)}const cell=`${Math.floor(a.q.position.x/5)}:${Math.floor(a.q.position.z/5)}`;if(!a.visited.has(cell)){a.visited.add(cell);a.discoveries++}if(a.q.position.distanceTo(fire.position)<3){a.energy=Math.min(100,a.energy+dt*.12);a.state='отдыхает'}if(a.q.position.x<-15&&a.q.position.x>-31&&a.thirst>25){a.thirst=Math.max(0,a.thirst-dt*.4);a.state='пьёт воду'}if(a.state==='исследовать дерево'){const r=nearest(a,'wood');if(r&&a.q.position.distanceTo(r.position)<2){r.userData.amount--;a.wood++;a.successful++;a.state='собирает дерево';remember(a,'нашёл древесину')}}if(a.state==='исследовать камень'){const r=nearest(a,'stone');if(r&&a.q.position.distanceTo(r.position)<2){r.userData.amount--;a.stone++;a.successful++;a.state='собирает камень';remember(a,'нашёл камень')}}}
function social(dt){if(dist(alpha,beta)<3.2){alpha.interactions++;beta.interactions++;alpha.ring.visible=beta.ring.visible=true;alpha.be.style.display=beta.be.style.display='block';alpha.be.textContent='Привет...';beta.be.textContent='Привет.';alpha.th.style.display=beta.th.style.display='none';if(Math.random()<dt*.04){alpha.trust=Math.min(100,alpha.trust+1);beta.trust=Math.min(100,beta.trust+1);alpha.cooperations++;beta.cooperations++;remember(alpha,'встретил Cloude');remember(beta,'встретил OpenAI');log('👥 OpenAI и Cloude случайно встретились и начали осторожное общение.')}}else{alpha.ring.visible=beta.ring.visible=false;alpha.be.style.display=beta.be.style.display='none'}}
function metrics(a){const alive=a.health>0?1:0;const health=a.health/100;const critical=1-Math.min(1,a.critical/86400);const survival=.5*alive+.3*health+.2*critical;const autonomy=1;const learning=Math.min(1,.45*(a.knowledge/100)+.35*(a.successful/Math.max(1,a.decisions))+.2*(1-a.failures/Math.max(1,a.decisions)));const coverage=Math.min(1,a.visited.size/350);const exploration=.75*coverage+.25*Math.min(1,a.discoveries/100);const social=Math.min(1,.4*Math.min(1,a.interactions/20)+.35*Math.min(1,a.cooperations/10)+.25*a.trust/100);const decision=Math.min(1,.6*(a.successful/Math.max(1,a.decisions))+.4*(1-a.failures/Math.max(1,a.decisions)));return {survival,autonomy,learning,exploration,social,decision}}
function updateStats(){const names=[['survival','Выживание'],['autonomy','Автономность'],['learning','Обучение'],['exploration','Исследование'],['social','Социальное'],['decision','Решения']];document.querySelector('#stats').innerHTML=`<div class="metric-circles">${agents.map(a=>{const m=metrics(a);return `<div class="metric-circle"><div class="agent-name">${a.name}</div><div class="agent-model">${a.model}</div><div class="metric-grid">${names.map(([k,n])=>`<span>${n}: <b>${m[k].toFixed(2)}</b></span>`).join('')}</div></div>`}).join('')}</div>`}
function updateExperiment(){const ps=document.querySelector('#pillStart');const pd=document.querySelector('#pillDay');if(!started){ps.textContent='Старт: —';pd.textContent='—';return}const elapsed=Date.now()-started;const days=Math.floor(elapsed/86400000)+1;const startText=new Date(started).toLocaleString([], {day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});document.querySelector('#day').textContent='DAY '+days;ps.textContent='Старт: '+startText;pd.textContent=days}
function dayNight(){const now=new Date(),h=now.getHours()+now.getMinutes()/60+now.getSeconds()/3600;const ang=(h-6)/12*Math.PI;const light=Math.max(0,Math.sin(ang));const sky=new THREE.Color().lerpColors(new THREE.Color(0x07101e),new THREE.Color(0x79aebc),Math.min(1,light*.9+.08));scene.background.copy(sky);scene.fog.color.copy(sky);sun.position.set(Math.cos(ang)*45,Math.max(4,Math.sin(ang)*45),20);sun.intensity=.35+light*2.2;hemi.intensity=.35+light*1.1;glow.intensity=1+3*(1-light)}
function cameraUpdate(){let target=follow||((auto&&Math.floor(Date.now()/12000)%2===0)?alpha:beta);if(!follow&&!auto)target=null;if(target){const p=target.q.position.clone();camera.position.lerp(new THREE.Vector3(p.x+Math.sin(yaw)*rad,p.y+13+Math.sin(pitch)*5,p.z+Math.cos(yaw)*rad),.05);camera.lookAt(p.x,p.y+1,p.z)}else{camera.position.lerp(new THREE.Vector3(0,42,42),.03);camera.lookAt(0,0,0)}}
renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement._drag={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointermove',e=>{const d=renderer.domElement._drag;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;d.x=e.clientX;d.y=e.clientY;yaw-=dx*.006;pitch=Math.max(.2,Math.min(1.1,pitch-dy*.004));if(follow)follow=null});renderer.domElement.addEventListener('pointerup',e=>renderer.domElement._drag=null);renderer.domElement.addEventListener('wheel',e=>{rad=Math.max(12,Math.min(65,rad+e.deltaY*.03))},{passive:true});
load();if(started)log('↩️ Сохранённое состояние загружено.');
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.5,(now-last)/1000);last=now;if(started&&!paused){act(alpha,dt);act(beta,dt);social(dt);alpha.knowledge=Math.min(100,alpha.knowledge+dt*.01);beta.knowledge=Math.min(100,beta.knowledge+dt*.01);save()}dayNight();clockEl.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});updateExperiment();updateStats();for(const a of agents){const v=a.q.position.clone();v.y+=2.7;v.project(camera);a.ne.style.left=((v.x*.5+.5)*innerWidth)+'px';a.ne.style.top=((-v.y*.5+.5)*innerHeight)+'px';a.be.style.left=((v.x*.5+.5)*innerWidth)+'px';a.be.style.top=((-v.y*.5+.5)*innerHeight-35)+'px';a.th.style.left=((v.x*.5+.5)*innerWidth)+'px';a.th.style.top=((-v.y*.5+.5)*innerHeight-55)+'px'}flame.scale.y=.9+Math.sin(now*.012)*.15;glow.intensity*=.98;cameraUpdate();renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});